import React, { useState, useEffect } from 'react';
import VideoCompressor from './VideoCompressor';
// Corregimos la conexión con Firebase
import { db } from './firebase'; 
import { collection, addDoc, query, onSnapshot, serverTimestamp } from 'firebase/firestore';

function App() {
  const [uploading, setUploading] = useState(false);
    const [showSettings, setShowSettings] = useState(false);
      const [gallery, setGallery] = useState([]);
        
          const [token, setToken] = useState(localStorage.getItem('tg_token') || '');
            const [chatId, setChatId] = useState(localStorage.getItem('tg_chatid') || '');

              // Escuchamos la base de datos de forma simple
                useEffect(() => {
                    const q = query(collection(db, "media"));

                        const unsubscribe = onSnapshot(q, (snapshot) => {
                              const items = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
                                    // Ordenamos aquí para evitar errores de índices en Firebase
                                          const sortedItems = items.sort((a, b) => {
                                                  const timeA = a.timestamp?.seconds || 0;
                                                          const timeB = b.timestamp?.seconds || 0;
                                                                  return timeB - timeA;
                                                                        });
                                                                              setGallery(sortedItems);
                                                                                  });

                                                                                      return () => unsubscribe();
                                                                                        }, []);

                                                                                          const saveSettings = () => {
                                                                                              localStorage.setItem('tg_token', token);
                                                                                                  localStorage.setItem('tg_chatid', chatId);
                                                                                                      setShowSettings(false);
                                                                                                        };

                                                                                                          const handleUpload = async (fileUrl, fileName, fileSize) => {
                                                                                                              if (!token || !chatId) return alert('Configura tus llaves en ⚙️');
                                                                                                                  
                                                                                                                      setUploading(true);
                                                                                                                          try {
                                                                                                                                const response = await fetch(fileUrl);
                                                                                                                                      const blob = await response.blob();
                                                                                                                                            const formData = new FormData();
                                                                                                                                                  formData.append('chat_id', chatId);
                                                                                                                                                        formData.append('video', blob, fileName);

                                                                                                                                                              const tgRes = await fetch(`https://api.telegram.org/bot${token}/sendVideo`, {
                                                                                                                                                                      method: 'POST',
                                                                                                                                                                              body: formData
                                                                                                                                                                                    });
                                                                                                                                                                                          const tgData = await tgRes.json();

                                                                                                                                                                                                if (tgRes.ok) {
                                                                                                                                                                                                        // Guardamos en Firebase con el tiempo del servidor
                                                                                                                                                                                                                await addDoc(collection(db, "media"), {
                                                                                                                                                                                                                          fileName: fileName,
                                                                                                                                                                                                                                    fileSize: fileSize,
                                                                                                                                                                                                                                              chatId: chatId,
                                                                                                                                                                                                                                                        messageId: tgData.result.message_id,
                                                                                                                                                                                                                                                                  timestamp: serverTimestamp(),
                                                                                                                                                                                                                                                                            type: blob.type
                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                            alert('✅ ¡Video enviado con éxito!');
                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                          alert('Error en Telegram: ' + tgData.description);
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                    } catch (e) {
                                                                                                                                                                                                                                                                                                                          alert('Error de red: ' + e.message);
                                                                                                                                                                                                                                                                                                                              } finally {
                                                                                                                                                                                                                                                                                                                                    setUploading(false);
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                <div className="min-h-screen bg-black text-white p-4 font-sans">
                                                                                                                                                                                                                                                                                                                                                      <header className="flex justify-between items-center mb-6 border-b border-gray-800 pb-4">
                                                                                                                                                                                                                                                                                                                                                              <h1 className="text-xl font-bold text-blue-500 italic">CloudGallery</h1>
                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => setShowSettings(!showSettings)} className="p-2 bg-gray-900 rounded-full border border-gray-700">⚙️</button>
                                                                                                                                                                                                                                                                                                                                                                            </header>

                                                                                                                                                                                                                                                                                                                                                                                  {showSettings ? (
                                                                                                                                                                                                                                                                                                                                                                                          <div className="bg-gray-900 p-6 rounded-2xl border border-blue-900">
                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-lg font-bold mb-4">Configuración Telegram</h2>
                                                                                                                                                                                                                                                                                                                                                                                                              <input type="password" value={token} onChange={e => setToken(e.target.value)} className="w-full bg-gray-800 p-3 rounded-lg mb-4 text-sm" placeholder="Bot Token" />
                                                                                                                                                                                                                                                                                                                                                                                                                        <input value={chatId} onChange={e => setChatId(e.target.value)} className="w-full bg-gray-800 p-3 rounded-lg mb-6 text-sm" placeholder="Chat ID" />
                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={saveSettings} className="w-full bg-blue-600 py-3 rounded-xl font-bold uppercase text-xs tracking-widest">Guardar Cambios</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="bg-gray-900 p-5 rounded-3xl mb-8 border border-gray-800 shadow-2xl">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <VideoCompressor onVideoReady={handleUpload} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {uploading && <p className="text-[10px] text-blue-400 mt-4 animate-pulse text-center font-bold tracking-tighter">SUBIENDO ARCHIVO A LA NUBE...</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="text-[10px] font-bold text-gray-500 mb-4 uppercase tracking-[3px]">Galería de Medios</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="grid grid-cols-3 gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {gallery.length === 0 && <p className="col-span-3 text-center text-gray-700 py-10 text-[10px] italic">No hay archivos guardados aún</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {gallery.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={item.id} className="aspect-square bg-gray-900 rounded-xl flex flex-col items-center justify-center border border-gray-800 hover:border-blue-500 transition-all">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="w-10 h-10 bg-blue-900/20 rounded-full flex items-center justify-center mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <span className="text-sm">🎬</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <span className="px-2 text-[7px] text-gray-400 truncate w-full text-center font-mono uppercase">{item.fileName}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         export default App;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         