import React, { useState, useEffect } from 'react';
import VideoCompressor from './VideoCompressor';
import { db } from './firebase'; 
import { collection, addDoc, query, onSnapshot } from 'firebase/firestore';

function App() {
  const [uploading, setUploading] = useState(false);
    const [showSettings, setShowSettings] = useState(false);
      const [gallery, setGallery] = useState([]);
        
          const [token, setToken] = useState(localStorage.getItem('tg_token') || '');
            const [chatId, setChatId] = useState(localStorage.getItem('tg_chatid') || '');

              // Consulta simplificada sin filtros para evitar errores de índices
                useEffect(() => {
                    const q = query(collection(db, "media"));

                        const unsubscribe = onSnapshot(q, (snapshot) => {
                              const items = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
                                    // Ordenamos aquí en el celular, no en la base de datos, para que sea más fácil
                                          const sortedItems = items.sort((a, b) => b.timestamp?.seconds - a.timestamp?.seconds);
                                                setGallery(sortedItems);
                                                    });

                                                        return () => unsubscribe();
                                                          }, []);

                                                            const saveSettings = () => {
                                                                localStorage.setItem('tg_token', token);
                                                                    localStorage.setItem('tg_chatid', chatId);
                                                                        setShowSettings(false);
                                                                          };

                                                                            const handleUpload = async (fileUrl, fileName, fileSize) => {
                                                                                if (!token || !chatId) return alert('Configura tus llaves en ⚙️');
                                                                                    
                                                                                        setUploading(true);
                                                                                            try {
                                                                                                  const response = await fetch(fileUrl);
                                                                                                        const blob = await response.blob();
                                                                                                              const formData = new FormData();
                                                                                                                    formData.append('chat_id', chatId);
                                                                                                                          formData.append('video', blob, fileName);

                                                                                                                                const tgRes = await fetch(`https://api.telegram.org/bot${token}/sendVideo`, {
                                                                                                                                        method: 'POST',
                                                                                                                                                body: formData
                                                                                                                                                      });
                                                                                                                                                            const tgData = await tgRes.json();

                                                                                                                                                                  if (tgRes.ok) {
                                                                                                                                                                          await addDoc(collection(db, "media"), {
                                                                                                                                                                                    fileName: fileName,
                                                                                                                                                                                              fileSize: fileSize,
                                                                                                                                                                                                        chatId: chatId,
                                                                                                                                                                                                                  messageId: tgData.result.message_id,
                                                                                                                                                                                                                            timestamp: new Date(),
                                                                                                                                                                                                                                      type: blob.type
                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                        } catch (e) {
                                                                                                                                                                                                                                                              alert('Error: ' + e.message);
                                                                                                                                                                                                                                                                  } finally {
                                                                                                                                                                                                                                                                        setUploading(false);
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                    <div className="min-h-screen bg-black text-white p-4 font-sans">
                                                                                                                                                                                                                                                                                          <header className="flex justify-between items-center mb-6 border-b border-gray-800 pb-4">
                                                                                                                                                                                                                                                                                                  <h1 className="text-xl font-bold text-blue-500">CloudGallery</h1>
                                                                                                                                                                                                                                                                                                          <button onClick={() => setShowSettings(!showSettings)} className="p-2 bg-gray-900 rounded-full">⚙️</button>
                                                                                                                                                                                                                                                                                                                </header>

                                                                                                                                                                                                                                                                                                                      {showSettings ? (
                                                                                                                                                                                                                                                                                                                              <div className="bg-gray-900 p-6 rounded-2xl border border-blue-900 text-left">
                                                                                                                                                                                                                                                                                                                                        <h2 className="text-lg font-bold mb-4">Ajustes</h2>
                                                                                                                                                                                                                                                                                                                                                  <input type="password" value={token} onChange={e => setToken(e.target.value)} className="w-full bg-gray-800 p-3 rounded-lg mb-4 text-sm" placeholder="Token del Bot" />
                                                                                                                                                                                                                                                                                                                                                            <input value={chatId} onChange={e => setChatId(e.target.value)} className="w-full bg-gray-800 p-3 rounded-lg mb-6 text-sm" placeholder="Chat ID" />
                                                                                                                                                                                                                                                                                                                                                                      <button onClick={saveSettings} className="w-full bg-blue-600 py-3 rounded-xl font-bold">Vincular Galería</button>
                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                            <main>
                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-gray-900 p-5 rounded-2xl mb-8 border border-gray-800">
                                                                                                                                                                                                                                                                                                                                                                                                                  <VideoCompressor onVideoReady={handleUpload} />
                                                                                                                                                                                                                                                                                                                                                                                                                              {uploading && <p className="text-xs text-blue-400 mt-4 animate-pulse text-center">Subiendo...</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-[10px] font-bold text-gray-500 mb-4 uppercase tracking-[2px]">Recuerdos Guardados</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="grid grid-cols-3 gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {gallery.length === 0 && <p className="col-span-3 text-center text-gray-700 py-10 text-xs italic">La galería está vacía</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {gallery.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div key={item.id} className="aspect-square bg-gray-900 rounded-lg flex flex-col items-center justify-center border border-gray-800 p-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="w-full h-full bg-gray-800 rounded flex items-center justify-center mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <span className="text-[10px] text-blue-500">🎥</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <span className="text-[8px] text-gray-400 truncate w-full text-center">{item.fileName}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             export default App;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             