import React, { useState, useEffect } from 'react';
import VideoCompressor from './VideoCompressor';
import { db } from './firebase'; 
import { collection, addDoc, query, onSnapshot, serverTimestamp } from 'firebase/firestore';

function App() {
  const [uploading, setUploading] = useState(false);
    const [showSettings, setShowSettings] = useState(false);
      const [gallery, setGallery] = useState([]);
        const [token, setToken] = useState(localStorage.getItem('tg_token') || '');
          const [chatId, setChatId] = useState(localStorage.getItem('tg_chatid') || '');

            useEffect(() => {
                if (!db) return;
                    const q = query(collection(db, "media"));
                        const unsubscribe = onSnapshot(q, (snapshot) => {
                              const items = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
                                    setGallery(items);
                                        }, (err) => console.log("Error de conexión:", err));
                                            return () => unsubscribe();
                                              }, []);

                                                const handleUpload = async (fileUrl, fileName, fileSize) => {
                                                    if (!token || !chatId) return alert('Configura el Bot en ⚙️');
                                                        setUploading(true);
                                                            try {
                                                                  const response = await fetch(fileUrl);
                                                                        const blob = await response.blob();
                                                                              const formData = new FormData();
                                                                                    formData.append('chat_id', chatId);
                                                                                          formData.append('video', blob, fileName);

                                                                                                const tgRes = await fetch(`https://api.telegram.org/bot${token}/sendVideo`, {
                                                                                                        method: 'POST',
                                                                                                                body: formData
                                                                                                                      });
                                                                                                                            const tgData = await tgRes.json();

                                                                                                                                  if (tgRes.ok) {
                                                                                                                                          await addDoc(collection(db, "media"), {
                                                                                                                                                    fileName,
                                                                                                                                                              chatId,
                                                                                                                                                                        timestamp: serverTimestamp(),
                                                                                                                                                                                  type: blob.type
                                                                                                                                                                                          });
                                                                                                                                                                                                  alert('¡Guardado!');
                                                                                                                                                                                                        }
                                                                                                                                                                                                            } catch (e) {
                                                                                                                                                                                                                  alert('Error: ' + e.message);
                                                                                                                                                                                                                      } finally {
                                                                                                                                                                                                                            setUploading(false);
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                        <div className="min-h-screen bg-black text-white p-4 font-sans">
                                                                                                                                                                                                                                              <header className="flex justify-between items-center mb-6">
                                                                                                                                                                                                                                                      <h1 className="text-xl font-bold text-blue-500 italic">CloudGallery</h1>
                                                                                                                                                                                                                                                              <button onClick={() => setShowSettings(!showSettings)} className="text-xl">⚙️</button>
                                                                                                                                                                                                                                                                    </header>

                                                                                                                                                                                                                                                                          {showSettings ? (
                                                                                                                                                                                                                                                                                  <div className="bg-gray-900 p-6 rounded-2xl">
                                                                                                                                                                                                                                                                                            <input type="password" value={token} onChange={e => setToken(e.target.value)} className="w-full bg-gray-800 p-3 rounded mb-4" placeholder="Token" />
                                                                                                                                                                                                                                                                                                      <input value={chatId} onChange={e => setChatId(e.target.value)} className="w-full bg-gray-800 p-3 rounded mb-4" placeholder="Chat ID" />
                                                                                                                                                                                                                                                                                                                <button onClick={() => { localStorage.setItem('tg_token', token); localStorage.setItem('tg_chatid', chatId); setShowSettings(false); }} className="w-full bg-blue-600 p-3 rounded font-bold">VINCULAR</button>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                      <main>
                                                                                                                                                                                                                                                                                                                                                <div className="bg-gray-900 p-5 rounded-3xl mb-8 border border-gray-800">
                                                                                                                                                                                                                                                                                                                                                            <VideoCompressor onVideoReady={handleUpload} />
                                                                                                                                                                                                                                                                                                                                                                        {uploading && <p className="text-center text-blue-400 mt-2 animate-pulse">SUBIENDO...</p>}
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                            <div className="grid grid-cols-3 gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                        {gallery.map(item => (
                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={item.id} className="aspect-square bg-gray-900 rounded-lg flex items-center justify-center border border-gray-800 text-[8px] p-1 text-center truncate">
                                                                                                                                                                                                                                                                                                                                                                                                                                      🎬<br/>{item.fileName}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default App;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              